#!/usr/bin/python3

from sys import argv
from flask import Flask, request, abort
from os.path import join


app = Flask(__name__)

def parse_args():
    for i in range(len(argv)):
        if argv[i] == '-p':
            port = argv[i + 1]
        elif argv[i] == '-d':
            directory = argv[i + 1]
        elif argv[i] == '-h':
            host = argv[i + 1]
    return host, port, directory


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def return_file(path):
    global pref_dir
    path_suff = path
    print(path_suff)
    try:
        path = join(pref_dir, path_suff)
        print(path)
        return open(path).read()
    except BaseException as ex:
        print(ex)
        return abort(404)


host, port, pref_dir = parse_args()
app.run(host=host, port=port)
